name: Deploy to EC2

on:
  push:
    branches:
      - main 

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'  # Specify the Node.js version you're using
        
      - name: Set up SSH agent
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_KEY }}

      - name: Remove old build folder on EC2 (Optional Backup)
        run: |
          ssh -o StrictHostKeyChecking=no ubuntu@${{ secrets.IP }} << 'EOF'
            cd ${{ secrets.PATH }}

            # Option 2: Delete the old build folder
            rm -rf dist
          EOF

      - name: Copy new build files to EC2
        run: |
          scp -o StrictHostKeyChecking=no -r ./dist ubuntu@${{ secrets.IP}}:${{ secrets.PATH }}

      - name: Restart PM2 process on EC2
        run: |
          ssh -o StrictHostKeyChecking=no ubuntu@${{ secrets.IP}} << 'EOF'
            cd ${{ secrets.PATH }}
            # Restart your app using PM2
            pm2 reload all
          EOF
